# Generated by Django 4.2.14 on 2024-08-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_user_full_name_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
