# Generated by Django 4.2.15 on 2024-08-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_role_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permisions',
            field=models.ManyToManyField(related_name='roles', to='userauths.custompermision'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rols',
            field=models.ManyToManyField(related_name='users', to='userauths.role'),
        ),
    ]
