# Generated by Django 5.1.3 on 2024-11-18 22:52

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_role_permisions_alter_user_rols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permisions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rols',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomPermision',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
