# Generated by Django 5.1.3 on 2024-11-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_remove_role_permisions_remove_user_rols_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
